apiVersion: v1
kind: ConfigMap
metadata:
  name: climate-config
  namespace: climate-monitoring
  labels:
    app.kubernetes.io/part-of: climate-monitoring
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_HTTP_PORTS: '8080'
  Jwt__Issuer: ClimateMonitoring.Identity
  Jwt__Audience: ClimateMonitoring.Client
  Jwt__ExpirationMinutes: '60'
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: '5672'
  SensorService__BaseUrl: http://sensor-service:8080/
  AlertService__BaseUrl: http://alert-service:8080/
  EventService__BaseUrl: http://event-service:8080/
  RealtimeService__BaseUrl: http://monitoring-service:8080/
  Simulation__Enabled: 'false'
  Simulation__IntervalSeconds: '30'
  DemoSeed__Enabled: 'false'
  AdminSeed__Username: admin
  AdminSeed__Email: admin@example.invalid
