apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: climate-monitoring
resources:
- namespace.yaml
- configmap.yaml
- gateway/configmap.yaml
- frontend/configmap.yaml
- gateway/deployment.yaml
- gateway/service.yaml
- identity/deployment.yaml
- identity/service.yaml
- sensors/deployment.yaml
- sensors/service.yaml
- monitoring/deployment.yaml
- monitoring/service.yaml
- alerts/deployment.yaml
- alerts/service.yaml
- events/deployment.yaml
- events/service.yaml
- audit/deployment.yaml
- audit/service.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- rabbitmq/service.yaml
- rabbitmq/headless-service.yaml
- rabbitmq/statefulset.yaml
- rabbitmq/networkpolicy.yaml
