apiVersion: v1
kind: Secret
metadata:
  name: climate-secrets
  namespace: climate-monitoring
  labels:
    app.kubernetes.io/part-of: climate-monitoring
type: Opaque
stringData:
  JWT_SIGNING_KEY: REPLACE_WITH_RANDOM_SIGNING_KEY_AT_LEAST_32_CHARS
  INTERNAL_API_KEY: REPLACE_WITH_RANDOM_INTERNAL_KEY_AT_LEAST_32_CHARS
  RABBITMQ_USER: REPLACE_WITH_BROKER_USER
  RABBITMQ_PASSWORD: REPLACE_WITH_BROKER_PASSWORD
  RABBITMQ_ERLANG_COOKIE: REPLACE_WITH_RANDOM_ERLANG_COOKIE
  ADMIN_SEED_PASSWORD: REPLACE_WITH_STRONG_ADMIN_PASSWORD
  SQL_IDENTITY_CONNECTION: Server=sql-host.example.invalid,1433;Database=IdentityDb;User
    Id=REPLACE_WITH_SQL_USER;Password=REPLACE_WITH_SQL_PASSWORD;Encrypt=True;TrustServerCertificate=True
  SQL_SENSORS_CONNECTION: Server=sql-host.example.invalid,1433;Database=SensorDb;User
    Id=REPLACE_WITH_SQL_USER;Password=REPLACE_WITH_SQL_PASSWORD;Encrypt=True;TrustServerCertificate=True
  SQL_MONITORING_CONNECTION: Server=sql-host.example.invalid,1433;Database=MonitoringDb;User
    Id=REPLACE_WITH_SQL_USER;Password=REPLACE_WITH_SQL_PASSWORD;Encrypt=True;TrustServerCertificate=True
  SQL_ALERTS_CONNECTION: Server=sql-host.example.invalid,1433;Database=AlertDb;User
    Id=REPLACE_WITH_SQL_USER;Password=REPLACE_WITH_SQL_PASSWORD;Encrypt=True;TrustServerCertificate=True
  SQL_EVENTS_CONNECTION: Server=sql-host.example.invalid,1433;Database=EventDb;User
    Id=REPLACE_WITH_SQL_USER;Password=REPLACE_WITH_SQL_PASSWORD;Encrypt=True;TrustServerCertificate=True
  SQL_AUDIT_CONNECTION: Server=sql-host.example.invalid,1433;Database=AuditDb;User
    Id=REPLACE_WITH_SQL_USER;Password=REPLACE_WITH_SQL_PASSWORD;Encrypt=True;TrustServerCertificate=True
