apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: climate-monitoring
  labels:
    app.kubernetes.io/part-of: climate-monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: climate-monitoring
  ports:
  - name: http
    port: 8080
    targetPort: http
