apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: climate-monitoring
  labels:
    app.kubernetes.io/part-of: climate-monitoring
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/part-of: climate-monitoring
  template:
    metadata:
      labels: *id001
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: rabbitmq
        image: rabbitmq:4.1-management@sha256:3574a8edaca320282b9c848f0b2661566b7e74f52c1b590f401b10224d294642
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: climate-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: climate-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: climate-secrets
              key: RABBITMQ_ERLANG_COOKIE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_NODENAME
          value: rabbit@$(POD_NAME)
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: +S 2:2
        - name: RABBITMQ_CTL_ERL_ARGS
          value: +S 1:1
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - ping
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - ping
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
